### ISSUE TITLE
Distinguish primary and secondary messages

### ISSUE THREAD

**Issue by matthijskooijman** [wie-niet/brandmeldbot#2]
I was thinking a bit on the flood of messages that is currently generated, and I think it would be good if we could add some analysis of primary messages (the causes of things) and secondary messages (effects from a primary message). For example, when some smoke detector becomes faulty, this generates one "Storing" message, which would be the primary message, and a number of "Geactiveerd" messages for outputs (door magnets, fault reporting), which would be the secondaries.

It would be good if we could reflect this in the messages sent, to make it easier to quickly see the primaries, without them being drowned in the secondaries. Ideally, you would use something like `<summary>` and `<details>` to show only the primary initially and allow expanding the message to also show the secondaries, but I'm not sure if Element supports this bit of HTML (it seems there is no matrix-level spec for supported HTML yet...). An alternative would be to add some styling so primary messages are bigger/more colorful/with a border/etc. and secondaries are more muted, so it is easy to quickly scan for primaries.

As for deciding what is primary and what is secondary, here's some thoughts:
 - Ideally you would attach each secondary to the primary that caused it, so for each message, decide if it is secondary and if so, to which primary it belongs.
 - I think we can assume that all secondaries follow the primary that caused them directly, so this means there is only one "active" primary that a new secondary might belong to.
 - Maybe we can classify things as primary and secondary by just looking at each message in isolation. For example, "Alarm" is always primary, activating a sounder is always secondary. Combined with the previous point, this means that a secondary is always just associated with the previous primary.
 - I think that secondaries should follow their primary pretty much directly, so if there are no messages for a couple of seconds, you can forget about the active primary (i.e. no further secondaries to that primary will be triggered). Note that I intentionally said "no messages for a couple of seconds", not "a couple of seconds after the primary", since there might be many secondaries (i.e. all sirens activating one by one on alarm). It also seems that timestamp in the log messages themselves are not all equal in this case, probably because it takes some time to activate all (but a jump in these timestamps might be a good indication of the last secondary). If a message is triggered that would normally be secondary without a recent/active primary, it should probably just be flagged as primary to prevent it from getting lost.
 - In reality, I think there is a tree of cause and effect (e.g. detector alarm causes main alarm, which activates "alarmgever", which activates individual sirens, while the door magnets are also activated by the the main alarm, etc.), but in practice this is not really useful to know, just knowing the root cause of the tree of events is sufficient.
 - It might be good to have further separation of primary messages depending on urgency, e.g. sending to PC, or periodic protocol error reporting could have lower urgency (shown smaller/less obvious), while alarm (and maybe also faults) could have higher urgency. This is probably a separate feature, since this would mostly be to control notifications on clients.
 - Ideally, all logic would be generic, without having to hardcode or config any info about how our particular fire system is configured. I'm not entirely sure if this will be possible, though maybe we can use some prefixes in the input/output naming in the BMC to help us here.

Examples of a primary followed by secondaries.

### Alarm ###
```
08-12-2021  19:34:11
Alarm
Groep 019/123 [HBM      ]
00000010
- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:11
Hoofdalarm

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:11
Geactiveerd
Bewaakte uitg. 001

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:11
Geactiveerd
Alarmgever

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:11
Geactiveerd
Groep 020/123 [I/O.Mod  ].1->
Deurrmagneet
- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:12
Geactiveerd
Groep 017/002 [Slow.Wh  ]

- - - - - - - - - - - - - - - - - - - -
```

### Reset detector after alarm ###
This is when the hand detector is reset, or the smoke has cleared from around the smoke detector. It is a primary without any secondaries, since the main alarm is not automatically cleared (that needs a reset).
```
08-12-2021  19:34:22
In rust
Groep 019/123 [HBM      ]

- - - - - - - - - - - - - - - - - - - -
```

### Recover from alarm ###
This is a bit special, since the actual primary is "BMC Reset", but somehow the "In rust: Bewaakte uitg" are logged before it. For simplicity, I guess it would be ok to just make that message its own primary then, rather than figure out how this reordering works?

There is also the "Gebruikers code", which was entered to allow the reset to complete (but can also occur by itself). I guess it (and probably all other "Informatie" messages) can be considered primary, but not allow any secondaries (so any secondaries after them would become primary, just like after a timeout).
```
- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:42
Informatie
Gebruikers Code

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:42
In rust
Bewaakte uitg. 001

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:42
BMC Reset

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:42
In rust
Alarmgever

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:42
In rust
Groep 020/123 [I/O.Mod  ].1->
Deurrmagneet
- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:34:43
In rust
Groep 017/002 [Slow.Wh  ]

- - - - - - - - - - - - - - - - - - - -
```

### Programming the BMC ###
When sending info from the PC, it also re-reads what is sent afterwards, so this then generates two entries, with the second one being secondary. However, when just reading from the PC, the second one will be primary, so the status of the second one would depend on whether the first one is present. In practice, it is probably fine to just make both of these primary to keep things simple.
```
08-12-2021  19:32:33
Informatie
Programmering van PC ingelezen

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:32:35
Informatie
Progammering verzenden naar PC

- - - - - - - - - - - - - - - - - - - -
```

### Toggling fault sending ###
This is turning the fault sending on, it looks similar for turning it off.

```
08-12-2021  19:35:29
Aan
Doormeld-unit

- - - - - - - - - - - - - - - - - - - -
08-12-2021  19:35:29
Aan
Relais 001
Storingsdoormelding TSEC3000
- - - - - - - - - - - - - - - - - - - -
```
### Periodic protocol error logging ###
These are both primary, but should probably be low urgency/notices or so (though maybe higher urgency when the error count is non-zero?).

```
08-12-2021  20:00:00
Informatie
Ring 02 protocol error 00001

- - - - - - - - - - - - - - - - - - - -
08-12-2021  20:00:00
Informatie
Ring 01 protocol error 00002

- - - - - - - - - - - - - - - - - - - -
```

### Daily doormagnet test ###
These are two primaries really: Activating and deactivating a timer program daily to detach all door magnets. This entire sequence should really be low-urgency. It is slightly tricky that these are "Informatie", so the earlier idea to make all "Informatie" primary but without allowing secondaries doesn't work, so we do have to also look at the second line (match "Inforatie // Tijdprogramma" probably and then make that a primary with secondaries).
```
- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:00:00
Informatie
Tijdprogramma 01 Dag  / Geactiv
Daily test door magnets
- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:00:00
Geactiveerd
Groep 020/125 [I/O.Mod  ].1->
Deurmagneten

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:00:00
Geactiveerd
Groep 020/124 [I/O.Mod  ].1->
Deurmagneten

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:00:00
Geactiveerd
Relais 003
Deurmagneet Fablab

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:00:00
Geactiveerd
Groep 020/123 [I/O.Mod  ].1->
Deurrmagneet

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:01:00
Informatie
Tijdprogramma 01 Nacht / Niet ac
Daily test door magnets

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:01:00
In rust
Groep 020/125 [I/O.Mod  ].1->
Deurmagneten

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:01:00
In rust
Groep 020/124 [I/O.Mod  ].1->
Deurmagneten

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:01:00
In rust
Relais 003
Deurmagneet Fablab

- - - - - - - - - - - - - - - - - - - -
09-12-2021  05:01:00
In rust
Groep 020/123 [I/O.Mod  ].1->
Deurrmagneet

- - - - - - - - - - - - - - - - - - - -
```

### Single detector fault ###
Recovery is similar, but with "In rust"  instead of "Storing" or "Geactiveerd". It is slightly annoying that both of these use "In rust", since then it becomes harder to classify "In rust" as primary (when it clears a fault condition) or secondary (when it clears e.g. a door magnet output). Maybe some tracking of state could help here, or maybe just some simple heurstics, or a prefix in the output name or something like that.. 
```
09-12-2021  16:50:08
Storing 
Groep 001/071 [Opt.M    ]
D0.48a (tijdelijke kantine)
afwezig
- - - - - - - - - - - - - - - - - - - -
09-12-2021  16:50:08
Geactiveerd
Groep 020/122 [I/O.Mod  ].1->
Deurmagneet
- - - - - - - - - - - - - - - - - - - -
```

### Conclusions ###
From the above, we should probably draft some heuristics about what to classify as primary or secondary and see if we can find a simple ruleset for this (though as noted in the last section, distinguishing "In rust" might be tricky). No more time now, though :-)

**Comment by matthijskooijman** [comment]
I've given this a bit more thought, and here's my idea of how to classify messages.
 
Each message is assigned:
 - A type, which is primary or secondary
 - Whether the message can have secondaries
 - A priority (low/medium/high)

The first two determine how to group messages (secondaries with the preceding primary, as long as the timestamp is the same or one second above the previous message and the preceding primary allows secondaries. If either of those is not fulfilled, the secondary is upgraded to a primary). The priority determines how things are displayed/notified. I can imagine "high" has distinguishing markup and includes an @room highlight, while "low" becomes a notice. One thing that is important, is that a low-priority primary is distinguishable from a secondary (i.e. it should be clear where the list of secondaries ends and a new low priority primary starts, even if both use notices, but this is not an issue if we implement editing messages for secondaries).

The latter two are normally useful for primaries only (secondaries can have no further secondaries and follow the priority of their primary), but are also specified for secondaries in case a secondary is received without a preceding primary, in which case the message is "upgraded" to a primary automatically as suggested above.

For the lines in each message I'm using timestamp / status / subject / name in that order.

1. `status == "Alarm"` -> High priority primary with secondaries
2. `status == "Hoofdalarm"` -> High priority secondary with secondaries (this one is just to make sure that "Hoofdalarm" becomes high prio, even when not preceded by a regular alarm)
3. `status == "Storing"` -> High priority primary with secondaries
4. `status == "Geactiveerd"` -> Normal priority secondary without secondaries (without secondaries because I *think* this is never the cause of something, but I'm not entirely sure)
5. `status == "In rust"` -> Normal priority secondary with secondaries (this will often be triggered as a secondary, but might also be upgraded to a primary when triggered first)
6. `status == "BMC Reset"` ->  Normal priority primary with secondaries
7. `status == "Aan" || status == "Uit"` -> Normal priority secondary with secondaries (Also expected to occur as primary or secondary, for example when disabling all sounders or all doormeldingen, etc.)
8. `status == "Informatie" && subject matches "Ring .. protocol error 0000"` -> Low priority primary without secondaries
9.  `status == "Informatie" && subject matches "Ring .. protocol error ...."` -> Normal priority primary without secondaries
10.  `status == "Informatie" && subject matches "Tijdprogramma.*"` -> Low priority primary with secondaries 
11. `status == "Informatie"` -> Normal priority primary without secondaries
12. All others -> Normal priority primary without secondaries

I think with these rules there is a small chance of misclassifying something (in particuler "In rust") as secondary when it would be primary, but only when two of them occur at pretty much the same moment in time, which seems unlikely enough to be acceptable.

**Comment by wie-niet** [comment]
This issue is pretty much resolved
